name: Daily RSS Feed Update

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6 AM UTC
  workflow_dispatch:     # Allows manual triggering

jobs:
  update-rss-feed:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run RSS generator script
      run: python generate_rss.py

    - name: Commit and push updated RSS feed
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
        git add daily_newsletter.xml
        git commit -m 'Daily update of RSS feed' || echo "No changes to commit"
        git push

