name: Daily RSS Feed Update

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6 AM UTC
  workflow_dispatch:     # Allows manual triggering

jobs:
  update-rss-feed:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Required for pushing changes
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT_C }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run RSS generator script
      env:
        NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
      run: python generate_rss.py

    - name: Validate RSS feed
      run: |
        # Check if RSS file was created and has content
        if [ ! -f "daily_newsletter.xml" ]; then
          echo "Error: RSS file not created"
          exit 1
        fi
        
        # Check if file has valid XML structure
        if ! head -1 daily_newsletter.xml | grep -q "<?xml"; then
          echo "Error: Invalid XML structure"
          exit 1
        fi
        
        echo "RSS feed validation passed"

    - name: Commit and push updated RSS feed
      run: |
        git config --local user.name 'github-actions[bot]'
        git config --local user.email 'github-actions[bot]@users.noreply.github.com'
        
        # Check if there are changes
        if git diff --quiet daily_newsletter.xml; then
          echo "No changes to RSS feed"
        else
          git add daily_newsletter.xml
          git commit -m "Daily RSS feed update - $(date +'%Y-%m-%d %H:%M UTC')"
          git push
          echo "RSS feed updated and pushed"
        fi

    - name: Display feed stats
      run: |
        if [ -f "daily_newsletter.xml" ]; then
          echo "RSS feed statistics:"
          echo "File size: $(wc -c < daily_newsletter.xml) bytes"
          echo "Number of items: $(grep -c '<item>' daily_newsletter.xml || echo '0')"
          echo "Last updated: $(date)"
        fi
